spring:

  profiles:
    active: dev

  datasource:
    url: datasource_url
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging.level:
  project.academyshow: debug
  org.hibernate.SQL: debug

server:
  port: 8081

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: '*'
  allowed-headers: '*'
  exposed-headers: '*'
  max-age: 3600

# app property
app:
  filePath: '/Users/woo/upload-test'

# jwt
jwt:
  secret: 'jwt-secret'
  refresh-token-secret: 'refresh-jwt-secret'
  token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800
