spring:

  profiles:
    active: dev

  datasource:
    url: datasource_url
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8081
